# Generated by Django 6.0.2 on 2026-02-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_tokenduration_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_purchased_minutes',
            field=models.IntegerField(default=0, help_text='Total minutes purchased with course'),
        ),
        migrations.AddField(
            model_name='student',
            name='total_used_minutes',
            field=models.IntegerField(default=0, help_text='Total minutes used in completed sessions'),
        ),
    ]
