# Generated by Django 6.0.2 on 2026-02-23 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_total_purchased_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('package_type', models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('CUSTOM', 'Custom')], default='BASIC', max_length=20)),
                ('total_sessions', models.IntegerField(help_text='Number of driving sessions included')),
                ('fee', models.DecimalField(decimal_places=2, help_text='Total package fee', max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('includes_license_fee', models.BooleanField(default=False, help_text='Whether license fee is included')),
                ('includes_materials', models.BooleanField(default=False, help_text='Whether study materials are included')),
                ('validity_days', models.IntegerField(blank=True, help_text='Package validity in days', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='students.course')),
                ('session_duration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_packages', to='students.tokenduration')),
            ],
            options={
                'verbose_name': 'Course Package',
                'verbose_name_plural': 'Course Packages',
                'db_table': 'course_packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('package_type', models.CharField(choices=[('SINGLE', 'Single Session'), ('TRIAL', 'Trial Pack'), ('SHORT', 'Short Term'), ('INTENSIVE', 'Intensive')], default='SINGLE', max_length=20)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike'), ('SCOOTER', 'Scooter'), ('HEAVY_VEHICLE', 'Heavy Vehicle')], max_length=50)),
                ('total_sessions', models.IntegerField(help_text='Number of sessions in package')),
                ('fee', models.DecimalField(decimal_places=2, help_text='Total package fee', max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('validity_days', models.IntegerField(blank=True, help_text='Package validity in days (null for unlimited)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_duration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_packages', to='students.tokenduration')),
            ],
            options={
                'verbose_name': 'Guest Package',
                'verbose_name_plural': 'Guest Packages',
                'db_table': 'guest_packages',
                'ordering': ['-created_at'],
            },
        ),
    ]
