# Generated by Django 6.0.2 on 2026-03-02 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique permission identifier (e.g., 'accounting.manage_fiscal_years')", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable permission name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this permission allows')),
                ('category', models.CharField(help_text="Permission category for grouping (e.g., 'accounting', 'students', 'reports')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'permissions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin who created this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('ACCOUNTANT', 'Accountant'), ('INSTRUCTOR', 'Instructor'), ('RECEPTIONIST', 'Receptionist')], default='RECEPTIONIST', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Role name (e.g., 'Driving School Admin', 'Account Manager')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text="Description of this role's purpose")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Superuser who created this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissions granted to this role', related_name='roles', to='core.permission')),
            ],
            options={
                'verbose_name': 'Custom Role',
                'verbose_name_plural': 'Custom Roles',
                'db_table': 'custom_roles',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, help_text='Custom role assigned to this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.customrole'),
        ),
        migrations.AddField(
            model_name='user',
            name='additional_permissions',
            field=models.ManyToManyField(blank=True, help_text="Additional permissions beyond the role's permissions", related_name='users_with_additional', to='core.permission'),
        ),
    ]
