# Generated by Django 6.0.2 on 2026-02-22 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('students', '0002_tokenduration_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ADMISSION', 'Admission Fee'), ('DRIVING_SESSION', 'Driving Session'), ('LICENSE_FORM', 'License Form Assistance'), ('INSTANT_BILLING', 'Instant Billing'), ('OTHER', 'Other Income')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('ONLINE', 'Online Payment'), ('CARD', 'Card'), ('UPI', 'UPI')], default='CASH', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='accounting.invoice')),
                ('related_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='students.student')),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Income',
                'db_table': 'income',
                'ordering': ['-date'],
            },
        ),
    ]
