# Generated by Django 6.0.2 on 2026-02-23 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_income'),
        ('students', '0003_student_total_purchased_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='guest_address',
            field=models.TextField(blank=True, help_text='Guest customer address', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='guest_contact',
            field=models.CharField(blank=True, help_text='Guest customer contact', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='guest_name',
            field=models.CharField(blank=True, help_text='Guest customer name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_guest',
            field=models.BooleanField(default=False, help_text='True if this is a guest/walk-in customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='students.student'),
        ),
    ]
