# Generated by Django 6.0.2 on 2026-02-23 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_invoice_guest_address_invoice_guest_contact_and_more'),
        ('students', '0003_student_total_purchased_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMOFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MOTORCYCLE', 'Motorcycle'), ('SCOOTER', 'Scooter'), ('MOPED', 'Moped'), ('CAR', 'Car (Light Motor Vehicle)'), ('HEAVY_VEHICLE', 'Heavy Vehicle'), ('TRAILER', 'Trailer')], max_length=50, unique=True)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TMO Fee',
                'verbose_name_plural': 'TMO Fees',
                'db_table': 'tmo_fees',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='TMOTrialReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('applicant_name', models.CharField(max_length=200)),
                ('applicant_id', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('MOTORCYCLE', 'Motorcycle'), ('SCOOTER', 'Scooter'), ('MOPED', 'Moped'), ('CAR', 'Car (Light Motor Vehicle)'), ('HEAVY_VEHICLE', 'Heavy Vehicle'), ('TRAILER', 'Trailer')], max_length=50)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_date', models.DateField(auto_now_add=True)),
                ('payment_mode', models.CharField(default='CASH', max_length=50)),
            ],
            options={
                'verbose_name': 'TMO Trial Receipt',
                'verbose_name_plural': 'TMO Trial Receipts',
                'db_table': 'tmo_trial_receipts',
                'ordering': ['-receipt_date', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Income', 'verbose_name_plural': 'Income'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', '-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('ADMISSION', 'Admission Fee'), ('DRIVING_SESSION', 'Driving Session'), ('LICENSE_FORM', 'License Form'), ('INSTANT_BILLING', 'Instant Billing'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='income',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_entries', to='accounting.invoice'),
        ),
        migrations.AlterField(
            model_name='income',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('ONLINE', 'Online Payment'), ('CARD', 'Card'), ('UPI', 'UPI')], max_length=50),
        ),
        migrations.AlterField(
            model_name='income',
            name='related_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_entries', to='students.student'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('ONLINE', 'Online Payment'), ('CARD', 'Card'), ('UPI', 'UPI')], default='CASH', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='received_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
