# Generated by Django 6.0.2 on 2026-02-23 08:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_tmofee_tmotrialreceipt_alter_income_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Account code (e.g., 1000 for Cash)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Account name', max_length=200)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], help_text='Type of account', max_length=20)),
                ('normal_balance', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], help_text='Normal balance side for this account', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Account description', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this account is active')),
                ('is_contra', models.BooleanField(default=False, help_text='Whether this is a contra account')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Opening balance for the account', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_account', models.ForeignKey(blank=True, help_text='Parent account for hierarchical structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_accounts', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('date', models.DateField(help_text='Transaction date')),
                ('description', models.TextField(help_text='Description of the transaction')),
                ('reference_type', models.CharField(blank=True, help_text='Type of reference (Invoice, Payment, etc.)', max_length=50, null=True)),
                ('reference_id', models.PositiveIntegerField(blank=True, help_text='ID of the referenced object', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, help_text='Total debit amount', max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, help_text='Total credit amount', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, help_text='When the entry was posted', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'db_table': 'journal_entries',
                'ordering': ['-date', '-entry_number'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('narration', models.TextField(blank=True, help_text='Description for this line', null=True)),
                ('line_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Journal Entry Line',
                'verbose_name_plural': 'Journal Entry Lines',
                'db_table': 'journal_entry_lines',
                'ordering': ['journal_entry', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('particular', models.CharField(help_text='Description/narration', max_length=500)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, help_text='Running balance after this transaction', max_digits=15)),
                ('voucher_type', models.CharField(blank=True, help_text='Voucher type (JE, INV, PAY, etc.)', max_length=50, null=True)),
                ('voucher_number', models.CharField(blank=True, help_text='Voucher reference number', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='accounting.account')),
                ('journal_entry_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='accounting.journalentryline')),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'db_table': 'ledger',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['code'], name='accounts_code_1c75a8_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_type'], name='accounts_account_8fba74_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_active'], name='accounts_is_acti_5b02bd_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['entry_number'], name='journal_ent_entry_n_60b5dc_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['date'], name='journal_ent_date_c86966_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['status'], name='journal_ent_status_f21256_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['reference_type', 'reference_id'], name='journal_ent_referen_b51473_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['journal_entry'], name='journal_ent_journal_d48be9_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['account'], name='journal_ent_account_d36604_idx'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['account'], name='ledger_account_c689ca_idx'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['date'], name='ledger_date_d59614_idx'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['voucher_type', 'voucher_number'], name='ledger_voucher_85369f_idx'),
        ),
    ]
