# Generated by Django 6.0.2 on 2026-02-23 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_account_journalentry_journalentryline_ledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='accounting.journalentry'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SALARY', 'Salary & Wages'), ('FUEL', 'Fuel & Petroleum'), ('MAINTENANCE', 'Vehicle Maintenance'), ('RENT', 'Rent'), ('UTILITIES', 'Utilities'), ('OFFICE_SUPPLIES', 'Office Supplies'), ('INSURANCE', 'Insurance'), ('TAXES', 'Taxes'), ('MARKETING', 'Marketing'), ('VEHICLE_EXPENSE', 'Vehicle Expense'), ('OTHER', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('ONLINE', 'Online Payment'), ('CARD', 'Card'), ('UPI', 'UPI')], default='CASH', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, help_text='Vendor/Payer name', max_length=200, null=True)),
                ('reference_number', models.CharField(blank=True, help_text='Bill/Receipt number', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_records', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
