# Generated by Django 6.0.2 on 2026-02-24 23:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_income_journal_entry_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Asset name/identifier', max_length=200)),
                ('asset_type', models.CharField(choices=[('VEHICLE', 'Vehicle'), ('EQUIPMENT', 'Equipment'), ('FURNITURE', 'Furniture'), ('BUILDING', 'Building'), ('LAND', 'Land'), ('ELECTRONICS', 'Electronics'), ('OTHER', 'Other')], help_text='Type of asset', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the asset', null=True)),
                ('purchase_date', models.DateField(help_text='Date when asset was purchased')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Original purchase price', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('current_value', models.DecimalField(decimal_places=2, default=0, help_text='Current value after depreciation', max_digits=15)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=0, help_text='Annual depreciation rate in percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('useful_life', models.IntegerField(default=5, help_text='Useful life in years')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('DISPOSED', 'Disposed')], default='ACTIVE', help_text='Current status of the asset', max_length=50)),
                ('location', models.CharField(blank=True, help_text='Physical location of the asset', max_length=200, null=True)),
                ('reevaluation_date', models.DateField(blank=True, help_text='Last reevaluation date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'db_table': 'assets',
                'ordering': ['-purchase_date', 'name'],
                'indexes': [models.Index(fields=['asset_type'], name='assets_asset_t_fc4c39_idx'), models.Index(fields=['status'], name='assets_status_326766_idx'), models.Index(fields=['purchase_date'], name='assets_purchas_fa81d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetReevaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_value', models.DecimalField(decimal_places=2, help_text='Value before reevaluation', max_digits=15)),
                ('new_value', models.DecimalField(decimal_places=2, help_text='Value after reevaluation', max_digits=15)),
                ('reevaluation_date', models.DateField(auto_now_add=True, help_text='Date of reevaluation')),
                ('reason', models.TextField(help_text='Reason for reevaluation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(help_text='Asset being reevaluated', on_delete=django.db.models.deletion.CASCADE, related_name='reevaluation_history', to='accounting.asset')),
                ('evaluated_by', models.ForeignKey(blank=True, help_text='User who performed the reevaluation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_reevaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Reevaluation',
                'verbose_name_plural': 'Asset Reevaluations',
                'db_table': 'asset_reevaluations',
                'ordering': ['-reevaluation_date', '-created_at'],
            },
        ),
    ]
