# Generated by Django 6.0.2 on 2026-02-25 02:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_asset_assetreevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the shareholder or company', max_length=200)),
                ('shareholder_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company'), ('PARTNERSHIP', 'Partnership'), ('TRUST', 'Trust'), ('OTHER', 'Other')], default='INDIVIDUAL', help_text='Type of shareholder', max_length=50)),
                ('contact_person', models.CharField(blank=True, help_text='Contact person for company shareholders', max_length=200, null=True)),
                ('address', models.TextField(blank=True, help_text='Address of the shareholder', null=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254, null=True)),
                ('pan_number', models.CharField(blank=True, help_text='PAN number for tax purposes', max_length=20, null=True)),
                ('date_became_shareholder', models.DateField(help_text='Date when this entity became a shareholder')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this shareholder is currently active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shareholder',
                'verbose_name_plural': 'Shareholders',
                'db_table': 'shareholders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShareHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_class', models.CharField(choices=[('EQUITY', 'Equity Shares'), ('PREFERENCE', 'Preference Shares'), ('DEBENTURE', 'Debentures')], default='EQUITY', help_text='Class of shares', max_length=50)),
                ('number_of_shares', models.IntegerField(default=0, help_text='Number of shares held', validators=[django.core.validators.MinValueValidator(0)])),
                ('face_value_per_share', models.DecimalField(decimal_places=2, default=Decimal('10'), help_text='Face value per share', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Total amount paid for these shares', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('certificate_number', models.CharField(blank=True, help_text='Share certificate number', max_length=50, null=True)),
                ('issue_date', models.DateField(help_text='Date when shares were issued')),
                ('is_fully_paid', models.BooleanField(default=True, help_text='Whether the shares are fully paid up')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shareholder', models.ForeignKey(help_text='The shareholder who owns these shares', on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='accounting.shareholder')),
            ],
            options={
                'verbose_name': 'Share Holding',
                'verbose_name_plural': 'Share Holdings',
                'db_table': 'share_holdings',
                'ordering': ['-issue_date', 'shareholder'],
            },
        ),
        migrations.CreateModel(
            name='ShareTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('TRANSFER', 'Transfer'), ('BONUS', 'Bonus Issue'), ('SPLIT', 'Stock Split'), ('BUYBACK', 'Buyback')], help_text='Type of transaction', max_length=20)),
                ('number_of_shares', models.IntegerField(help_text='Number of shares in this transaction')),
                ('price_per_share', models.DecimalField(decimal_places=2, help_text='Price per share', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total transaction amount', max_digits=15)),
                ('transaction_date', models.DateField(help_text='Date of transaction')),
                ('notes', models.TextField(blank=True, help_text='Transaction notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_shareholder', models.ForeignKey(blank=True, help_text='For transfers: shareholder transferring shares', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='accounting.shareholder')),
                ('shareholder', models.ForeignKey(help_text='Shareholder involved in the transaction', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.shareholder')),
                ('to_shareholder', models.ForeignKey(blank=True, help_text='For transfers: shareholder receiving shares', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='accounting.shareholder')),
            ],
            options={
                'verbose_name': 'Share Transaction',
                'verbose_name_plural': 'Share Transactions',
                'db_table': 'share_transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
