# Generated by Django 6.0.2 on 2026-02-25 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_shareholder_shareholding_sharetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholding',
            name='shareholder',
            field=models.ForeignKey(help_text='The shareholder who owns these shares', on_delete=django.db.models.deletion.CASCADE, related_name='shareholdings', to='accounting.shareholder'),
        ),
    ]
