# Generated by Django 6.0.2 on 2026-02-25 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_shareholding_shareholder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Fiscal year name (e.g., '2080/81', '2081/82')", max_length=50, unique=True)),
                ('start_date', models.DateField(help_text='Start date of fiscal year (B.S.)')),
                ('end_date', models.DateField(help_text='End date of fiscal year (B.S.)')),
                ('is_closed', models.BooleanField(default=False, help_text='Whether the fiscal year is closed and locked')),
                ('closed_at', models.DateTimeField(blank=True, help_text='Timestamp when fiscal year was closed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about the fiscal year', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, help_text='User who closed the fiscal year', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_fiscal_years', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fiscal Year',
                'verbose_name_plural': 'Fiscal Years',
                'db_table': 'fiscal_years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, help_text='Fiscal year for this transaction', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.fiscalyear'),
        ),
    ]
