# Generated by Django 6.0.2 on 2026-02-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_fiscalyear_journalentry_fiscal_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='income',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='income',
            name='related_student',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
