# Generated by Django 6.0.2 on 2026-03-02 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_remove_income_expense_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalyear',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this fiscal year (superuser only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fiscal_years', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='end_date',
            field=models.DateField(help_text='End date of fiscal year in A.D. (Ashad last of next year)'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='name',
            field=models.CharField(help_text="Fiscal year name (e.g., '2081/82', '2082/83')", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='start_date',
            field=models.DateField(help_text='Start date of fiscal year in A.D. (Shrawan 1 of the year)'),
        ),
    ]
